sudo: required
services: 
    - docker

before_install:
    - docker build -t vish0309/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vish0309/docker-react npm run test -- --coverage