sudo: required
services: 
    - docker

before_install:
    - docker build -t vish0309/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vish0309/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket-name: "elasticbeanstalk-ap-south-1-902119023307"
    bucket-path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"