sudo: required
services: 
    - docker

before_install:
    - docker build -t vish0309/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vish0309/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "Docker"
    env: "Docker-env"
    bucket-name: "elasticbeanstalk-us-east-1-902119023307"
    bucket-path: "Docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY